#!/usr/bin/env bash
source .environment

backup_folder="backups"
data_path="data"
backup_paths=("conf" "data")

# Use provided backup name
if [ -z ${1+x} ]; then 
    backup=$backup_folder/`date +%Y-%m-%d-%T`
else
    backup=$backup_folder/$1
fi

mkdir -p $backup_folder
mkdir $backup

for i in "${backup_paths[@]}"; do
    echo "Backing up $i"
    mkdir -p $backup/$i
    cp -R $data_path/dokuwiki/$i/ $backup/$i/
done

echo -e "${GREEN}Backed up your Dokuwiki to ${BLUE}${backup}${NC}"
