version: '3.2'
services:
  wiki:
    build: build/
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
    volumes:
      # Your dokuwiki data, mapped into the data folder
      - ./data/:/config/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin