version: '3.2'
services:
  wiki:
    #image: ghcr.io/linuxserver/dokuwiki
    build: .
    ports:
      - 8085:80
    restart: unless-stopped
    #volumes:
      #- ./local.php:/config/dokuwiki/conf/local.php
      #- ./data/:/app/dokuwiki/data # this is just cache?
      #- ./local.php:/config/dokuwiki/conf/userstyle.css
      # - ./config/:/config/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    networks:
      - database
      - proxy
networks:
  proxy:
    external: true
  database:
