#!/usr/bin/env sh
set -e

backup_folder="backups"
data_folder="data"

# Use provided backup name
if [ -z ${1+x} ]; then 
    backup=`ls backups | tail -n 1`
else
    backup=$1
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

[ "$(ls data)" ] && echo "${RED}The data folder is not empty!${NC} Operation aborted to prevent data loss. " && exit 1

echo "Restoring backup $backup"
cp -r $backup_folder/$backup/* $data_folder/

echo "${GREEN}Backup ${BLUE}${backup}${NC} has been restored"