#!/usr/bin/env bash
source .environment

backup_folder="backups"
data_folder="data"

# Use provided backup name
if [ -z ${1+x} ]; then 
    backup=`ls backups | tail -n 1`
else
    backup=$1
fi

echo -e "Do you want to restore the backup ${BLUE}${backup}${NC}? ${RED}This will lead to the loss of the data currently in your wiki${NC}. "
echo "Press enter to continue or ctrl+c to cancel. "
read REPLY

echo "Restoring backup $backup"
cp -R $backup_folder/$backup/* $data_folder/

echo -e "${GREEN}Backup ${BLUE}${backup}${NC} has been restored"
