#!/usr/bin/env sh
set -e

backup_folder="backups"
data_folder="data"

# Use provided backup name
if [ -z ${1+x} ]; then 
    backup=`ls backups | tail -n 1`
else
    backup=$1
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "Do you want to restore the backup ${BLUE}${backup}${NC}? ${RED}This will lead to the loss of the data currently in your wiki${NC}. "
echo "Press enter to continue or ctrl+c to cancel. "
read REPLY

echo "Restoring backup $backup"
cp -R $backup_folder/$backup/* $data_folder/

echo "${GREEN}Backup ${BLUE}${backup}${NC} has been restored"
