#!/usr/bin/env bash
set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Only act if the container isn't already running
if ./.is-running; then
    echo "${GREEN}Your Dokuwiki is already running! :-)${NC}" # Or there was a change in the docker-compose CLI. Oops!
    exit 0
fi

# Clean up old container
docker-compose down

docker-compose up -d

echo "${GREEN}Your Dokuwiki should be up in a few seconds${NC}"
echo "If you didn't make any changes, it should be available at ${BLUE}http://localhost:8080${NC}."
