#!/usr/bin/env bash
source .environment

# Only act if the container isn't already running
if ./.is-running; then
    echo -e "${GREEN}Your Dokuwiki is already running! :-)${NC}" # Or there was a change in the docker-compose CLI. Oops!
    exit 0
fi

# Clean up old container
docker-compose down

docker-compose up -d

echo -e "${GREEN}Your Dokuwiki should be up in a few seconds${NC}"
echo -e "If you didn't make any changes, it should be available at ${BLUE}http://localhost:8080${NC}."
