#!/usr/bin/env bash
source .environment

echo "Upgrade your Dokuwiki? Your pages will be backed up and restored. Your installed plugins and some other data may be lost in the process. "
echo "Press enter to continue or ctrl+c to cancel. "
read REPLY

# Stop container if it is running
restart_container=false
if ./.is-running; then
    echo "Stopping your Dokuwiki"
    restart_container=true
    ./stop
fi

./backup

echo "Tearing down your previous installation"
docker-compose down
rm -r data/*

echo "Building your new & improved Dokuwiki"
docker build build/ --pull

./restore

echo "${GREEN}Your Dokuwiki has been upgraded. ${NC}"

# Start the container if it was runnng before
restart_container=false
if [ $restart_container == true ]; then
    echo "Starting your Dokuwiki again"
    ./start
fi
